name: delivery_marketplace
publish_to: 'none'
description: Delivery Marketplace - on-demand customer/delivery partner app
version: 1.0.0+18

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.4.0
  firebase_messaging: ^15.2.0
  cloud_functions: ^5.6.0
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.12.3
  geolocator: ^13.0.2
  url_launcher: ^6.3.2
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  razorpay_flutter: ^1.4.0
  flutter_webrtc: ^1.6.2+hotfix.3
  qr_flutter: ^4.1.0

flutter:
  uses-material-design: true
